import { ConstructReductionConfig } from "@constructs/ast/_abstract/_types";
import { InteractionContext } from "@constructs/ast/_abstract/_types/interaction/context/interactionContext";
import { ReductionLifecycleController } from "@constructs/ast/_abstract/_util/reduce/_util/lifecycle/types";
import getValueGeneratorAsync from "@constructs/ast/_abstract/_util/reduce/async/_util/getValueGeneratorAsync";
import { runEvaluationLifecycleAsync } from "@constructs/ast/_abstract/_util/reduce/async/_util/lifecycle/eval";
import { ComponentValueGenerationProcessorAsync } from "@constructs/ast/_abstract/_util/reduce/async/_util/types/componentProcessor";

/**
 * Returns a function that iterates over the values of a construct component
 *
 * @param reductionConfig
 * @param lifecycle
 */
export function getValueGenerationProcessorAsync<Context extends InteractionContext, Intermediate = any>(
    reductionConfig: ConstructReductionConfig<Context>,
    lifecycle: ReductionLifecycleController
): ComponentValueGenerationProcessorAsync<Context, Intermediate> {
    return async ({ component, context, subject }): Promise<[Promise<Intermediate>[], Context]> => {

        const mut = { values: [], context: context } as { values: Promise<Intermediate>[], context: Context };

        /**
         * For each location generated by the component,
         *  derive a subject and run the evaluation lifecycle method on it
         * @param step
         */
        async function processLocationStep(step: [any, Context]) {
            if (!Array.isArray(step)) {
                mut.context = step;
                return false;
            }

            const subject   = await reductionConfig.deriveSubject(step, component.name, true);
            const evaluated = await runEvaluationLifecycleAsync(lifecycle, [subject, context]);

            mut.context = evaluated.context;
            mut.values.push(...(evaluated.values as Promise<Intermediate>[]));
            return true;
        }


        // loop over each generated value
        {
            let promise;
            const componentValueGenerator = getValueGeneratorAsync(component, subject, context);
            while ((promise = componentValueGenerator.next())) {
                const { done, value: componentLocationStep } = await promise;
                if (done) {
                    mut.context = componentLocationStep;
                    break;
                }
                const okay = await processLocationStep(componentLocationStep);
                if (okay) break;
            }
        }

        // next step
        return [mut.values, mut.context ?? context];
    };
}
